// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.11
// source: proto/routes.proto

package routes

import (
	gobgp "github.com/p3rdy/bgpemu/proto/gobgp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RouteDeployment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopoName string   `protobuf:"bytes,1,opt,name=topo_name,json=topoName,proto3" json:"topo_name,omitempty"`
	Routes   []*Route `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty"`
}

func (x *RouteDeployment) Reset() {
	*x = RouteDeployment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_routes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteDeployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteDeployment) ProtoMessage() {}

func (x *RouteDeployment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteDeployment.ProtoReflect.Descriptor instead.
func (*RouteDeployment) Descriptor() ([]byte, []int) {
	return file_proto_routes_proto_rawDescGZIP(), []int{0}
}

func (x *RouteDeployment) GetTopoName() string {
	if x != nil {
		return x.TopoName
	}
	return ""
}

func (x *RouteDeployment) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

type Route struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MrtPath *string       `protobuf:"bytes,2,opt,name=mrt_path,json=mrtPath,proto3,oneof" json:"mrt_path,omitempty"`
	Paths   []*gobgp.Path `protobuf:"bytes,3,rep,name=paths,proto3" json:"paths,omitempty"`
}

func (x *Route) Reset() {
	*x = Route{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_routes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_proto_routes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_proto_routes_proto_rawDescGZIP(), []int{1}
}

func (x *Route) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Route) GetMrtPath() string {
	if x != nil && x.MrtPath != nil {
		return *x.MrtPath
	}
	return ""
}

func (x *Route) GetPaths() []*gobgp.Path {
	if x != nil {
		return x.Paths
	}
	return nil
}

var File_proto_routes_proto protoreflect.FileDescriptor

var file_proto_routes_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x1a, 0x17, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x62, 0x67, 0x70, 0x2f, 0x67, 0x6f, 0x62, 0x67, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x55, 0x0a, 0x0f, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x44, 0x65,
	0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x70, 0x6f,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x6f, 0x70,
	0x6f, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x2e, 0x52,
	0x6f, 0x75, 0x74, 0x65, 0x52, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x22, 0x6b, 0x0a, 0x05,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x08, 0x6d, 0x72, 0x74,
	0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6d,
	0x72, 0x74, 0x50, 0x61, 0x74, 0x68, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a, 0x05, 0x70, 0x61, 0x74,
	0x68, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x61, 0x70, 0x69, 0x70, 0x62,
	0x2e, 0x50, 0x61, 0x74, 0x68, 0x52, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x42, 0x0b, 0x0a, 0x09,
	0x5f, 0x6d, 0x72, 0x74, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x42, 0x0e, 0x5a, 0x0c, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_routes_proto_rawDescOnce sync.Once
	file_proto_routes_proto_rawDescData = file_proto_routes_proto_rawDesc
)

func file_proto_routes_proto_rawDescGZIP() []byte {
	file_proto_routes_proto_rawDescOnce.Do(func() {
		file_proto_routes_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_routes_proto_rawDescData)
	})
	return file_proto_routes_proto_rawDescData
}

var file_proto_routes_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_routes_proto_goTypes = []interface{}{
	(*RouteDeployment)(nil), // 0: routes.RouteDeployment
	(*Route)(nil),           // 1: routes.Route
	(*gobgp.Path)(nil),      // 2: apipb.Path
}
var file_proto_routes_proto_depIdxs = []int32{
	1, // 0: routes.RouteDeployment.routes:type_name -> routes.Route
	2, // 1: routes.Route.paths:type_name -> apipb.Path
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_routes_proto_init() }
func file_proto_routes_proto_init() {
	if File_proto_routes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_routes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteDeployment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_routes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Route); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_routes_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_routes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_routes_proto_goTypes,
		DependencyIndexes: file_proto_routes_proto_depIdxs,
		MessageInfos:      file_proto_routes_proto_msgTypes,
	}.Build()
	File_proto_routes_proto = out.File
	file_proto_routes_proto_rawDesc = nil
	file_proto_routes_proto_goTypes = nil
	file_proto_routes_proto_depIdxs = nil
}
