// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.11
// source: proto/scene.proto

package scene

import (
	gobgp "github.com/p3rdy/bgpemu/proto/gobgp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Scene struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopoName     string      `protobuf:"bytes,1,opt,name=topo_name,json=topoName,proto3" json:"topo_name,omitempty"`
	Inits        []*Behavior `protobuf:"bytes,2,rep,name=inits,proto3" json:"inits,omitempty"`
	RoutesPath   string      `protobuf:"bytes,3,opt,name=routes_path,json=routesPath,proto3" json:"routes_path,omitempty"`
	PoliciesPath string      `protobuf:"bytes,4,opt,name=policies_path,json=policiesPath,proto3" json:"policies_path,omitempty"`
	Behaviors    []*Behavior `protobuf:"bytes,5,rep,name=behaviors,proto3" json:"behaviors,omitempty"`
}

func (x *Scene) Reset() {
	*x = Scene{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Scene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scene) ProtoMessage() {}

func (x *Scene) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scene.ProtoReflect.Descriptor instead.
func (*Scene) Descriptor() ([]byte, []int) {
	return file_proto_scene_proto_rawDescGZIP(), []int{0}
}

func (x *Scene) GetTopoName() string {
	if x != nil {
		return x.TopoName
	}
	return ""
}

func (x *Scene) GetInits() []*Behavior {
	if x != nil {
		return x.Inits
	}
	return nil
}

func (x *Scene) GetRoutesPath() string {
	if x != nil {
		return x.RoutesPath
	}
	return ""
}

func (x *Scene) GetPoliciesPath() string {
	if x != nil {
		return x.PoliciesPath
	}
	return ""
}

func (x *Scene) GetBehaviors() []*Behavior {
	if x != nil {
		return x.Behaviors
	}
	return nil
}

type Behavior struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DeviceName string  `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	IsAsync    bool    `protobuf:"varint,3,opt,name=is_async,json=isAsync,proto3" json:"is_async,omitempty"`
	Steps      []*Step `protobuf:"bytes,4,rep,name=steps,proto3" json:"steps,omitempty"`
}

func (x *Behavior) Reset() {
	*x = Behavior{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Behavior) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Behavior) ProtoMessage() {}

func (x *Behavior) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Behavior.ProtoReflect.Descriptor instead.
func (*Behavior) Descriptor() ([]byte, []int) {
	return file_proto_scene_proto_rawDescGZIP(), []int{1}
}

func (x *Behavior) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Behavior) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *Behavior) GetIsAsync() bool {
	if x != nil {
		return x.IsAsync
	}
	return false
}

func (x *Behavior) GetSteps() []*Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

type Step struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are assignable to Body:
	//
	//	*Step_Cmds
	//	*Step_Wait
	//	*Step_File
	//	*Step_Sbs
	//	*Step_Aps
	Body isStep_Body `protobuf_oneof:"body"`
}

func (x *Step) Reset() {
	*x = Step{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Step) ProtoMessage() {}

func (x *Step) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Step.ProtoReflect.Descriptor instead.
func (*Step) Descriptor() ([]byte, []int) {
	return file_proto_scene_proto_rawDescGZIP(), []int{2}
}

func (x *Step) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *Step) GetBody() isStep_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *Step) GetCmds() *Commands {
	if x, ok := x.GetBody().(*Step_Cmds); ok {
		return x.Cmds
	}
	return nil
}

func (x *Step) GetWait() *Wait {
	if x, ok := x.GetBody().(*Step_Wait); ok {
		return x.Wait
	}
	return nil
}

func (x *Step) GetFile() *FileTrans {
	if x, ok := x.GetBody().(*Step_File); ok {
		return x.File
	}
	return nil
}

func (x *Step) GetSbs() *StartBgpStep {
	if x, ok := x.GetBody().(*Step_Sbs); ok {
		return x.Sbs
	}
	return nil
}

func (x *Step) GetAps() *AddPeerStep {
	if x, ok := x.GetBody().(*Step_Aps); ok {
		return x.Aps
	}
	return nil
}

type isStep_Body interface {
	isStep_Body()
}

type Step_Cmds struct {
	Cmds *Commands `protobuf:"bytes,2,opt,name=cmds,proto3,oneof"`
}

type Step_Wait struct {
	Wait *Wait `protobuf:"bytes,3,opt,name=wait,proto3,oneof"`
}

type Step_File struct {
	File *FileTrans `protobuf:"bytes,4,opt,name=file,proto3,oneof"`
}

type Step_Sbs struct {
	Sbs *StartBgpStep `protobuf:"bytes,5,opt,name=sbs,proto3,oneof"`
}

type Step_Aps struct {
	Aps *AddPeerStep `protobuf:"bytes,6,opt,name=aps,proto3,oneof"`
}

func (*Step_Cmds) isStep_Body() {}

func (*Step_Wait) isStep_Body() {}

func (*Step_File) isStep_Body() {}

func (*Step_Sbs) isStep_Body() {}

func (*Step_Aps) isStep_Body() {}

type Commands struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Container string   `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	Cmds      []string `protobuf:"bytes,2,rep,name=cmds,proto3" json:"cmds,omitempty"`
}

func (x *Commands) Reset() {
	*x = Commands{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Commands) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commands) ProtoMessage() {}

func (x *Commands) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commands.ProtoReflect.Descriptor instead.
func (*Commands) Descriptor() ([]byte, []int) {
	return file_proto_scene_proto_rawDescGZIP(), []int{3}
}

func (x *Commands) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *Commands) GetCmds() []string {
	if x != nil {
		return x.Cmds
	}
	return nil
}

type Wait struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time      uint32 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Timestamp uint64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *Wait) Reset() {
	*x = Wait{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Wait) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wait) ProtoMessage() {}

func (x *Wait) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wait.ProtoReflect.Descriptor instead.
func (*Wait) Descriptor() ([]byte, []int) {
	return file_proto_scene_proto_rawDescGZIP(), []int{4}
}

func (x *Wait) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Wait) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type FileTrans struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src string `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Des string `protobuf:"bytes,2,opt,name=des,proto3" json:"des,omitempty"`
}

func (x *FileTrans) Reset() {
	*x = FileTrans{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileTrans) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTrans) ProtoMessage() {}

func (x *FileTrans) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTrans.ProtoReflect.Descriptor instead.
func (*FileTrans) Descriptor() ([]byte, []int) {
	return file_proto_scene_proto_rawDescGZIP(), []int{5}
}

func (x *FileTrans) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *FileTrans) GetDes() string {
	if x != nil {
		return x.Des
	}
	return ""
}

type AddPeerStep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Peers []*gobgp.Peer `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
}

func (x *AddPeerStep) Reset() {
	*x = AddPeerStep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPeerStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPeerStep) ProtoMessage() {}

func (x *AddPeerStep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPeerStep.ProtoReflect.Descriptor instead.
func (*AddPeerStep) Descriptor() ([]byte, []int) {
	return file_proto_scene_proto_rawDescGZIP(), []int{6}
}

func (x *AddPeerStep) GetPeers() []*gobgp.Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type StartBgpStep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Global *gobgp.Global         `protobuf:"bytes,1,opt,name=global,proto3" json:"global,omitempty"`
	Rpki   *gobgp.AddRpkiRequest `protobuf:"bytes,2,opt,name=rpki,proto3" json:"rpki,omitempty"`
}

func (x *StartBgpStep) Reset() {
	*x = StartBgpStep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scene_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartBgpStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBgpStep) ProtoMessage() {}

func (x *StartBgpStep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scene_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBgpStep.ProtoReflect.Descriptor instead.
func (*StartBgpStep) Descriptor() ([]byte, []int) {
	return file_proto_scene_proto_rawDescGZIP(), []int{7}
}

func (x *StartBgpStep) GetGlobal() *gobgp.Global {
	if x != nil {
		return x.Global
	}
	return nil
}

func (x *StartBgpStep) GetRpki() *gobgp.AddRpkiRequest {
	if x != nil {
		return x.Rpki
	}
	return nil
}

var File_proto_scene_proto protoreflect.FileDescriptor

var file_proto_scene_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x1a, 0x17, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x67, 0x6f, 0x62, 0x67, 0x70, 0x2f, 0x67, 0x6f, 0x62, 0x67, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xc0, 0x01, 0x0a, 0x05, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x74, 0x6f, 0x70, 0x6f, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x74, 0x6f, 0x70, 0x6f, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x69, 0x6e,
	0x69, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x63, 0x65, 0x6e,
	0x65, 0x2e, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x52, 0x05, 0x69, 0x6e, 0x69, 0x74,
	0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x5f, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x50, 0x61,
	0x74, 0x68, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x5f, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x6f, 0x6c, 0x69, 0x63,
	0x69, 0x65, 0x73, 0x50, 0x61, 0x74, 0x68, 0x12, 0x2d, 0x0a, 0x09, 0x62, 0x65, 0x68, 0x61, 0x76,
	0x69, 0x6f, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x63, 0x65,
	0x6e, 0x65, 0x2e, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x52, 0x09, 0x62, 0x65, 0x68,
	0x61, 0x76, 0x69, 0x6f, 0x72, 0x73, 0x22, 0x7d, 0x0a, 0x08, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69,
	0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x61, 0x73,
	0x79, 0x6e, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x41, 0x73, 0x79,
	0x6e, 0x63, 0x12, 0x21, 0x0a, 0x05, 0x73, 0x74, 0x65, 0x70, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x2e, 0x53, 0x74, 0x65, 0x70, 0x52, 0x05,
	0x73, 0x74, 0x65, 0x70, 0x73, 0x22, 0xe5, 0x01, 0x0a, 0x04, 0x53, 0x74, 0x65, 0x70, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x63, 0x6d, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x73, 0x48, 0x00, 0x52, 0x04, 0x63, 0x6d, 0x64, 0x73, 0x12, 0x21, 0x0a, 0x04, 0x77, 0x61, 0x69,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x2e,
	0x57, 0x61, 0x69, 0x74, 0x48, 0x00, 0x52, 0x04, 0x77, 0x61, 0x69, 0x74, 0x12, 0x26, 0x0a, 0x04,
	0x66, 0x69, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x63, 0x65,
	0x6e, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x48, 0x00, 0x52, 0x04,
	0x66, 0x69, 0x6c, 0x65, 0x12, 0x27, 0x0a, 0x03, 0x73, 0x62, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x42,
	0x67, 0x70, 0x53, 0x74, 0x65, 0x70, 0x48, 0x00, 0x52, 0x03, 0x73, 0x62, 0x73, 0x12, 0x26, 0x0a,
	0x03, 0x61, 0x70, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x63, 0x65,
	0x6e, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x65, 0x65, 0x72, 0x53, 0x74, 0x65, 0x70, 0x48, 0x00,
	0x52, 0x03, 0x61, 0x70, 0x73, 0x42, 0x06, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x3c, 0x0a,
	0x08, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6d, 0x64, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6d, 0x64, 0x73, 0x22, 0x38, 0x0a, 0x04, 0x57,
	0x61, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x2f, 0x0a, 0x09, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x73, 0x72, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x64, 0x65, 0x73, 0x22, 0x30, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x50, 0x65, 0x65,
	0x72, 0x53, 0x74, 0x65, 0x70, 0x12, 0x21, 0x0a, 0x05, 0x70, 0x65, 0x65, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x61, 0x70, 0x69, 0x70, 0x62, 0x2e, 0x50, 0x65, 0x65,
	0x72, 0x52, 0x05, 0x70, 0x65, 0x65, 0x72, 0x73, 0x22, 0x60, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x42, 0x67, 0x70, 0x53, 0x74, 0x65, 0x70, 0x12, 0x25, 0x0a, 0x06, 0x67, 0x6c, 0x6f, 0x62,
	0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x70, 0x62,
	0x2e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x52, 0x06, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x12,
	0x29, 0x0a, 0x04, 0x72, 0x70, 0x6b, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x61, 0x70, 0x69, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x70, 0x6b, 0x69, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x04, 0x72, 0x70, 0x6b, 0x69, 0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_scene_proto_rawDescOnce sync.Once
	file_proto_scene_proto_rawDescData = file_proto_scene_proto_rawDesc
)

func file_proto_scene_proto_rawDescGZIP() []byte {
	file_proto_scene_proto_rawDescOnce.Do(func() {
		file_proto_scene_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_scene_proto_rawDescData)
	})
	return file_proto_scene_proto_rawDescData
}

var file_proto_scene_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_scene_proto_goTypes = []interface{}{
	(*Scene)(nil),                // 0: scene.Scene
	(*Behavior)(nil),             // 1: scene.Behavior
	(*Step)(nil),                 // 2: scene.Step
	(*Commands)(nil),             // 3: scene.Commands
	(*Wait)(nil),                 // 4: scene.Wait
	(*FileTrans)(nil),            // 5: scene.FileTrans
	(*AddPeerStep)(nil),          // 6: scene.AddPeerStep
	(*StartBgpStep)(nil),         // 7: scene.StartBgpStep
	(*gobgp.Peer)(nil),           // 8: apipb.Peer
	(*gobgp.Global)(nil),         // 9: apipb.Global
	(*gobgp.AddRpkiRequest)(nil), // 10: apipb.AddRpkiRequest
}
var file_proto_scene_proto_depIdxs = []int32{
	1,  // 0: scene.Scene.inits:type_name -> scene.Behavior
	1,  // 1: scene.Scene.behaviors:type_name -> scene.Behavior
	2,  // 2: scene.Behavior.steps:type_name -> scene.Step
	3,  // 3: scene.Step.cmds:type_name -> scene.Commands
	4,  // 4: scene.Step.wait:type_name -> scene.Wait
	5,  // 5: scene.Step.file:type_name -> scene.FileTrans
	7,  // 6: scene.Step.sbs:type_name -> scene.StartBgpStep
	6,  // 7: scene.Step.aps:type_name -> scene.AddPeerStep
	8,  // 8: scene.AddPeerStep.peers:type_name -> apipb.Peer
	9,  // 9: scene.StartBgpStep.global:type_name -> apipb.Global
	10, // 10: scene.StartBgpStep.rpki:type_name -> apipb.AddRpkiRequest
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_scene_proto_init() }
func file_proto_scene_proto_init() {
	if File_proto_scene_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_scene_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Scene); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scene_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Behavior); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scene_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Step); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scene_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Commands); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scene_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Wait); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scene_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileTrans); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scene_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPeerStep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scene_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartBgpStep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_scene_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Step_Cmds)(nil),
		(*Step_Wait)(nil),
		(*Step_File)(nil),
		(*Step_Sbs)(nil),
		(*Step_Aps)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_scene_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_scene_proto_goTypes,
		DependencyIndexes: file_proto_scene_proto_depIdxs,
		MessageInfos:      file_proto_scene_proto_msgTypes,
	}.Build()
	File_proto_scene_proto = out.File
	file_proto_scene_proto_rawDesc = nil
	file_proto_scene_proto_goTypes = nil
	file_proto_scene_proto_depIdxs = nil
}
