// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.11
// source: proto/astopo.proto

package astopo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Topology struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Nodes []*ASNode `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Links []*ASLink `protobuf:"bytes,3,rep,name=links,proto3" json:"links,omitempty"`
}

func (x *Topology) Reset() {
	*x = Topology{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_astopo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Topology) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topology) ProtoMessage() {}

func (x *Topology) ProtoReflect() protoreflect.Message {
	mi := &file_proto_astopo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topology.ProtoReflect.Descriptor instead.
func (*Topology) Descriptor() ([]byte, []int) {
	return file_proto_astopo_proto_rawDescGZIP(), []int{0}
}

func (x *Topology) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Topology) GetNodes() []*ASNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Topology) GetLinks() []*ASLink {
	if x != nil {
		return x.Links
	}
	return nil
}

type ASNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Asn int32  `protobuf:"varint,1,opt,name=asn,proto3" json:"asn,omitempty"`
	Net string `protobuf:"bytes,2,opt,name=net,proto3" json:"net,omitempty"`
}

func (x *ASNode) Reset() {
	*x = ASNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_astopo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ASNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASNode) ProtoMessage() {}

func (x *ASNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_astopo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASNode.ProtoReflect.Descriptor instead.
func (*ASNode) Descriptor() ([]byte, []int) {
	return file_proto_astopo_proto_rawDescGZIP(), []int{1}
}

func (x *ASNode) GetAsn() int32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *ASNode) GetNet() string {
	if x != nil {
		return x.Net
	}
	return ""
}

type ASLink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ANode int32 `protobuf:"varint,1,opt,name=a_node,json=aNode,proto3" json:"a_node,omitempty"`
	ZNode int32 `protobuf:"varint,2,opt,name=z_node,json=zNode,proto3" json:"z_node,omitempty"`
}

func (x *ASLink) Reset() {
	*x = ASLink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_astopo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ASLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASLink) ProtoMessage() {}

func (x *ASLink) ProtoReflect() protoreflect.Message {
	mi := &file_proto_astopo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASLink.ProtoReflect.Descriptor instead.
func (*ASLink) Descriptor() ([]byte, []int) {
	return file_proto_astopo_proto_rawDescGZIP(), []int{2}
}

func (x *ASLink) GetANode() int32 {
	if x != nil {
		return x.ANode
	}
	return 0
}

func (x *ASLink) GetZNode() int32 {
	if x != nil {
		return x.ZNode
	}
	return 0
}

var File_proto_astopo_proto protoreflect.FileDescriptor

var file_proto_astopo_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x73, 0x74, 0x6f, 0x70, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x73, 0x74, 0x6f, 0x70, 0x6f, 0x22, 0x6a, 0x0a, 0x08,
	0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x05,
	0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x73,
	0x74, 0x6f, 0x70, 0x6f, 0x2e, 0x41, 0x53, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x05, 0x6e, 0x6f, 0x64,
	0x65, 0x73, 0x12, 0x24, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x73, 0x74, 0x6f, 0x70, 0x6f, 0x2e, 0x41, 0x53, 0x4c, 0x69, 0x6e,
	0x6b, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x22, 0x2c, 0x0a, 0x06, 0x41, 0x53, 0x4e, 0x6f,
	0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x73, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x61, 0x73, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6e, 0x65, 0x74, 0x22, 0x36, 0x0a, 0x06, 0x41, 0x53, 0x4c, 0x69, 0x6e, 0x6b,
	0x12, 0x15, 0x0a, 0x06, 0x61, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x7a, 0x5f, 0x6e, 0x6f, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x7a, 0x4e, 0x6f, 0x64, 0x65, 0x42, 0x26,
	0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x33, 0x72,
	0x64, 0x79, 0x2f, 0x62, 0x67, 0x70, 0x65, 0x6d, 0x75, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x61, 0x73, 0x74, 0x6f, 0x70, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_astopo_proto_rawDescOnce sync.Once
	file_proto_astopo_proto_rawDescData = file_proto_astopo_proto_rawDesc
)

func file_proto_astopo_proto_rawDescGZIP() []byte {
	file_proto_astopo_proto_rawDescOnce.Do(func() {
		file_proto_astopo_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_astopo_proto_rawDescData)
	})
	return file_proto_astopo_proto_rawDescData
}

var file_proto_astopo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_astopo_proto_goTypes = []interface{}{
	(*Topology)(nil), // 0: astopo.Topology
	(*ASNode)(nil),   // 1: astopo.ASNode
	(*ASLink)(nil),   // 2: astopo.ASLink
}
var file_proto_astopo_proto_depIdxs = []int32{
	1, // 0: astopo.Topology.nodes:type_name -> astopo.ASNode
	2, // 1: astopo.Topology.links:type_name -> astopo.ASLink
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_astopo_proto_init() }
func file_proto_astopo_proto_init() {
	if File_proto_astopo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_astopo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Topology); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_astopo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ASNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_astopo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ASLink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_astopo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_astopo_proto_goTypes,
		DependencyIndexes: file_proto_astopo_proto_depIdxs,
		MessageInfos:      file_proto_astopo_proto_msgTypes,
	}.Build()
	File_proto_astopo_proto = out.File
	file_proto_astopo_proto_rawDesc = nil
	file_proto_astopo_proto_goTypes = nil
	file_proto_astopo_proto_depIdxs = nil
}
